# Generated by Django 5.1.1 on 2024-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shoe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cat', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'shoex_table',
            },
        ),
    ]
