# Generated by Django 5.1.1 on 2024-09-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
